version: '2'

services:

  mysql-db:
    image: "mysql:latest"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    environment:
      DB_USERNAME: root
      DB_NAME: api
      DB_HOST: mysql-db
      DB_PORT: 3307
      NODE_ENV: "development"
    ports:
      - "8001:8001"
    depends_on:
      - mysql-db
